import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { roleHasPermission } from '@/lib/auth/permissions';
import { approveExternalAiAction, configureExternalAiAction, disableExternalAiAction } from './actions';

export default async function ExternalAiSettingsPage(){
  const c=await requireServerAuthContext(); const canConfigure=roleHasPermission(c.activeRole,'ai.settings.configure'); const canApprove=roleHasPermission(c.activeRole,'ai.settings.approve'); if(!canConfigure&&!canApprove)throw new Error('غير مصرح بإدارة إعدادات External AI.'); const s=await createServerSupabaseClient(); const {data,error}=await s.from('organization_ai_settings').select('*').eq('organization_id',c.organizationId).single(); if(error)throw new Error('تعذر تحميل إعدادات External AI.');
  return <section className="space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Privacy-Gated External AI</p><h1 className="mt-2 text-3xl font-black">إعدادات الخصوصية ومزوّد AI الخارجي</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">التكوين التقني لا يفعّل AI تلقائيًا. مسؤول النظام يحدد المزوّد ومنطقة المعالجة وسياسة الاحتفاظ، ثم يلزم اعتماد خصوصية منفصل من MANAGEMENT_APPROVER قبل التفعيل.</p></header>
    <div className="grid gap-4 md:grid-cols-3"><State title="External AI" value={data.external_ai_enabled?'ENABLED':'DISABLED'} tone={data.external_ai_enabled?'ok':'muted'}/><State title="Privacy Approval" value={data.privacy_approved?'APPROVED':'NOT APPROVED'} tone={data.privacy_approved?'ok':'warn'}/><State title="Processing Region" value={String(data.processing_region??'Not configured')} tone="muted"/></div>
    {canConfigure?<form action={configureExternalAiAction} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">تكوين المزوّد</h2><p className="mt-2 text-xs leading-6 text-slate-500">أي تعديل على المزوّد أو المنطقة يلغي الاعتماد السابق ويعيد External AI إلى Disabled حتى إعادة الموافقة.</p><div className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Provider<input name="provider" defaultValue={String(data.provider??'')} required placeholder="Configured provider name" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">Processing Region<input name="processingRegion" defaultValue={String(data.processing_region??'')} required placeholder="Documented region" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold md:col-span-2">Retention Policy<input name="retentionPolicy" defaultValue={String(data.retention_policy??'')} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label></div><button className="mt-4 rounded-xl bg-slate-900 px-5 py-3 text-sm font-black text-white">حفظ التكوين وتعطيل AI لحين الاعتماد</button></form>:null}
    {canApprove&&!data.external_ai_enabled?<form action={approveExternalAiAction} className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><h2 className="text-xl font-black text-violet-950">اعتماد الخصوصية والتفعيل</h2><p className="mt-2 text-xs leading-6 text-violet-800">لا تعتمد قبل التحقق من PDPL، نقل البيانات عبر الحدود، المنطقة، الغرض، والاحتفاظ وفق سياسة المؤسسة.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">مرجع قرار/موافقة الخصوصية<input name="approvalReference" required className="mt-2 w-full rounded-xl border border-violet-300 bg-white px-3 py-2.5"/></label><label className="text-xs font-bold">ملاحظة الاعتماد<input name="approvalNote" className="mt-2 w-full rounded-xl border border-violet-300 bg-white px-3 py-2.5"/></label></div><button className="mt-4 rounded-xl bg-violet-900 px-5 py-3 text-sm font-black text-white">اعتماد وتفعيل External AI</button></form>:null}
    {data.external_ai_enabled?<form action={disableExternalAiAction} className="rounded-2xl border border-red-200 bg-red-50 p-5"><h2 className="font-black text-red-950">تعطيل External AI</h2><p className="mt-2 text-xs text-red-800">التعطيل متاح فورًا كإجراء أمان ولا يحذف سجل الاعتماد السابق.</p><div className="mt-4 flex flex-wrap gap-3"><input name="reason" required placeholder="سبب التعطيل" className="min-w-64 flex-1 rounded-xl border border-red-300 bg-white px-3 py-2.5 text-sm"/><button className="rounded-xl bg-red-800 px-4 py-2.5 text-sm font-bold text-white">تعطيل</button></div></form>:null}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 text-xs leading-7 text-slate-600 shadow-sm"><strong className="text-slate-900">الوضع الحالي:</strong> Provider = {String(data.provider??'—')} · Region = {String(data.processing_region??'—')} · Approval reference = {String(data.privacy_approval_reference??'—')} · Approved at = {String(data.approved_at??'—')}</section>
  </section>;
}
function State({title,value,tone}:{title:string;value:string;tone:'ok'|'warn'|'muted'}){const cls=tone==='ok'?'bg-emerald-50 text-emerald-900':tone==='warn'?'bg-amber-50 text-amber-900':'bg-slate-50 text-slate-800';return <div className={`rounded-2xl border border-slate-200 p-5 ${cls}`}><span className="text-xs font-bold opacity-70">{title}</span><strong className="mt-2 block text-lg">{value}</strong></div>}
