import Link from 'next/link';
import { roleHasPermission } from '@/lib/auth/permissions';
import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { approveFollowupPolicyAction, approveMethodologyAction, configureFollowupPolicyAction, configureMethodologyAction, markActivityConductedAction } from './actions';

export default async function ImpactPage(){
  const context=await requireServerAuthContext('impact.view');
  const canConfigure=roleHasPermission(context.activeRole,'methodology.configure');
  const canApprove=roleHasPermission(context.activeRole,'methodology.approve');
  const canManage=roleHasPermission(context.activeRole,'impact.manage');
  const supabase=await createServerSupabaseClient();
  const [policyResult,methodResult,activityResult,externalResult]=await Promise.all([
    supabase.from('impact_followup_policies').select('*,impact_followup_policy_levels(*)').eq('organization_id',context.organizationId).order('created_at',{ascending:false}),
    supabase.from('impact_methodology_versions').select('*').eq('organization_id',context.organizationId).order('created_at',{ascending:false}),
    supabase.from('activities').select('id,activity_code,title_ar,title_en,internal_state').eq('organization_id',context.organizationId).in('internal_state',['EXTERNAL_TRACKING','IMPACT_FOLLOWUP','FINAL_IMPACT_REPORT','ANNUAL_REPORTING','ARCHIVED']).order('updated_at',{ascending:false}),
    supabase.from('external_submission_records').select('activity_id,status,accreditation_number').eq('organization_id',context.organizationId),
  ]);
  if(policyResult.error||methodResult.error||activityResult.error||externalResult.error) throw new Error('تعذر تحميل مساحة قياس الأثر.');
  const externalByActivity=new Map((externalResult.data??[]).map(r=>[String(r.activity_id),r]));
  const activePolicy=(policyResult.data??[]).find(p=>p.status==='ACTIVE'); const activeMethod=(methodResult.data??[]).find(m=>m.status==='ACTIVE');
  const draftsPolicy=(policyResult.data??[]).filter(p=>p.status==='DRAFT'); const draftsMethod=(methodResult.data??[]).filter(m=>m.status==='DRAFT');

  return <section className="space-y-6">
    <header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
      <p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Impact Intelligence</p><h1 className="mt-2 text-3xl font-black">قياس الأثر وHTVI</h1>
      <p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">L1–L4 تُدار بمواعيد متابعة Versioned. كل نسخة سياسة مرتبطة بفترة سريان؛ الأنشطة التاريخية تستخدم النسخة التي كانت نافذة يوم التنفيذ. لا يعيد النظام تطبيع أوزان HTVI، ولا يصدر HTVI نهائيًا ما دام مكوّن مطلوب غير مكتمل.</p>
    </header>

    <div className="grid gap-4 lg:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">FOLLOW-UP POLICY</p><h2 className="mt-1 text-xl font-black">{activePolicy?String(activePolicy.name):'لا توجد سياسة نشطة'}</h2></div>{activePolicy?<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-800">{String(activePolicy.version_label)}</span>:null}</div>
        {activePolicy?<><p className="mt-3 text-xs text-slate-500">سارية من {String(activePolicy.effective_from??'—')} إلى {String(activePolicy.effective_to??'مفتوح')}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">{((activePolicy.impact_followup_policy_levels??[]) as Array<Record<string,unknown>>).map(x=><div key={String(x.level)} className="rounded-xl bg-slate-50 p-3"><strong>{String(x.level)}</strong><span className="mt-1 block text-slate-500">+{String(x.due_offset_days)} يوم</span></div>)}</div></>:<p className="mt-4 text-sm text-amber-800">يلزم اعتماد سياسة متابعة قبل بدء قياس الأثر.</p>}
      </section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">HTVI METHODOLOGY</p><h2 className="mt-1 text-xl font-black">{activeMethod?`HTVI ${String(activeMethod.version_label)}`:'لا توجد منهجية نشطة'}</h2></div>{activeMethod?<span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-800">INTERNAL</span>:null}</div>
        {activeMethod?<pre className="mt-4 overflow-auto rounded-xl bg-slate-950 p-3 text-xs text-slate-100" dir="ltr">{JSON.stringify(activeMethod.weights,null,2)}</pre>:<p className="mt-4 text-sm text-amber-800">يلزم اعتماد منهجية HTVI قبل التقارير النهائية.</p>}
      </section>
    </div>

    {canConfigure?<details className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer font-black">إعداد نسخة جديدة من سياسة المتابعة والمنهجية</summary><div className="mt-5 grid gap-6 xl:grid-cols-2">
      <form action={configureFollowupPolicyAction} className="space-y-3"><h3 className="font-black">سياسة المتابعة</h3><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">الاسم<input name="name" required defaultValue="Impact Follow-up" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">الإصدار<input name="version" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">سارية من<input type="date" name="effectiveFrom" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">سارية إلى — اختياري<input type="date" name="effectiveTo" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label>{['L1','L2','L3','L4'].map(level=><div key={level} className="rounded-xl bg-slate-50 p-3"><strong>{level}</strong><div className="mt-2 grid grid-cols-2 gap-2"><label className="text-[10px] font-bold">Due offset<input type="number" min="0" name={`${level}Due`} required className="mt-1 w-full rounded-lg border border-slate-300 px-2 py-2"/></label><label className="text-[10px] font-bold">Grace<input type="number" min="0" name={`${level}Grace`} required className="mt-1 w-full rounded-lg border border-slate-300 px-2 py-2"/></label></div></div>)}</div><p className="text-xs leading-6 text-slate-500">عند اعتماد نسخة أحدث، تُغلق فترة النسخة السابقة تاريخيًا ولا يُعاد حساب الأنشطة التي سبق إنشاء جداول أثرها.</p><button className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">حفظ Draft Policy</button></form>
      <form action={configureMethodologyAction} className="space-y-3"><h3 className="font-black">منهجية HTVI</h3><label className="text-xs font-bold">الإصدار<input name="version" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><div className="grid grid-cols-4 gap-2">{[['L1',15],['L2',20],['L3',25],['L4',40]].map(([level,value])=><label key={String(level)} className="text-xs font-bold">{level}<input type="number" name={`${level}Weight`} defaultValue={Number(value)} required className="mt-2 w-full rounded-xl border border-slate-300 px-2 py-2.5"/></label>)}</div><div className="grid grid-cols-3 gap-2"><label className="text-xs font-bold">Excellent<input type="number" name="excellent" defaultValue="85" className="mt-2 w-full rounded-xl border border-slate-300 px-2 py-2.5"/></label><label className="text-xs font-bold">Very Good<input type="number" name="veryGood" defaultValue="75" className="mt-2 w-full rounded-xl border border-slate-300 px-2 py-2.5"/></label><label className="text-xs font-bold">Good<input type="number" name="good" defaultValue="65" className="mt-2 w-full rounded-xl border border-slate-300 px-2 py-2.5"/></label></div><button className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">حفظ Draft Methodology</button></form>
    </div></details>:null}

    {canApprove&&(draftsPolicy.length||draftsMethod.length)?<section className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><h2 className="font-black text-violet-950">إصدارات بانتظار الاعتماد الإداري</h2><div className="mt-4 flex flex-wrap gap-3">{draftsPolicy.map(p=><form key={String(p.id)} action={approveFollowupPolicyAction}><input type="hidden" name="policyId" value={String(p.id)}/><button className="rounded-xl bg-violet-900 px-4 py-2.5 text-sm font-bold text-white">اعتماد Policy {String(p.version_label)} · {String(p.effective_from??'بدون تاريخ')}</button></form>)}{draftsMethod.map(m=><form key={String(m.id)} action={approveMethodologyAction}><input type="hidden" name="methodologyId" value={String(m.id)}/><button className="rounded-xl bg-violet-900 px-4 py-2.5 text-sm font-bold text-white">اعتماد HTVI {String(m.version_label)}</button></form>)}</div></section>:null}

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">الأنشطة ومتابعة الأثر</h2><div className="mt-4 grid gap-3">{(activityResult.data??[]).length===0?<p className="text-sm text-slate-500">لا توجد أنشطة وصلت إلى مرحلة الأثر.</p>:(activityResult.data??[]).map(a=>{const ext=externalByActivity.get(String(a.id));return <article key={String(a.id)} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-slate-50 p-4"><div><div className="font-mono text-xs font-bold text-slate-500" dir="ltr">{String(a.activity_code)}</div><h3 className="mt-1 font-black">{String(a.title_ar)}</h3><p className="mt-1 text-xs text-slate-500">External: {String(ext?.status??'—')} · Internal: {String(a.internal_state)}</p></div><div className="flex flex-wrap gap-2">{String(a.internal_state)==='EXTERNAL_TRACKING'&&String(ext?.status)==='APPROVED'&&canManage&&activePolicy?<form action={markActivityConductedAction} className="flex gap-2"><input type="hidden" name="activityId" value={String(a.id)}/><input type="datetime-local" name="conductedAt" required className="rounded-xl border border-slate-300 px-3 py-2 text-xs"/><button className="rounded-xl bg-teal-800 px-3 py-2 text-xs font-bold text-white">تأكيد تنفيذ النشاط</button></form>:null}{['IMPACT_FOLLOWUP','FINAL_IMPACT_REPORT','ANNUAL_REPORTING','ARCHIVED'].includes(String(a.internal_state))?<Link href={`/impact/${String(a.id)}`} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">فتح قياس الأثر</Link>:null}</div></article>})}</div></section>
  </section>;
}
