import Link from 'next/link';
import { roleHasPermission } from '@/lib/auth/permissions';
import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { acknowledgeAnnualReportAction, approveAnnualReportAction, generateAnnualReportAction } from './actions';

export default async function AnnualReportsPage(){
  const c=await requireServerAuthContext('annual.view'); const canGenerate=roleHasPermission(c.activeRole,'annual.generate'); const canApprove=roleHasPermission(c.activeRole,'annual.approve_committee'); const canAck=roleHasPermission(c.activeRole,'annual.acknowledge'); const s=await createServerSupabaseClient();
  const {data:reports,error}=await s.from('annual_committee_reports').select('*').eq('organization_id',c.organizationId).order('reporting_year',{ascending:false}); if(error)throw new Error('تعذر تحميل التقارير السنوية.');
  const ids=(reports??[]).map(r=>r.id); const {data:metrics}=ids.length?await s.from('annual_report_metrics').select('*').eq('organization_id',c.organizationId).in('annual_report_id',ids):{data:[]}; const byReport=new Map<string,Record<string,unknown>[]>(); for(const m of metrics??[]){const key=String(m.annual_report_id);byReport.set(key,[...(byReport.get(key)??[]),m]);}
  const currentYear=new Date().getFullYear();
  return <section className="space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Annual Governance Intelligence</p><h1 className="mt-2 text-3xl font-black">التقرير السنوي لأداء اللجنة العلمية</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">تقرير إداري داخلي يولد من البيانات المتراكمة، يعتمد من رئيس اللجنة ثم يرفع للإدارة للإقرار. لا يُعرض كمتطلب سنوي مسمى من الهيئة.</p></header>
    {canGenerate?<form action={generateAnnualReportAction} className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="text-xs font-bold">السنة<input name="year" type="number" min="2000" max="2200" defaultValue={currentYear} className="mt-2 block rounded-xl border border-slate-300 px-3 py-2.5"/></label><button className="rounded-xl bg-teal-800 px-5 py-3 text-sm font-black text-white">توليد / تحديث مسودة التقرير</button><p className="text-xs text-slate-500">التوليد يعيد حساب المؤشرات من قاعدة البيانات، ولا يختلق أرقامًا.</p></form>:null}
    <div className="grid gap-4">{(reports??[]).length===0?<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">لا توجد تقارير سنوية بعد.</div>:(reports??[]).map(report=>{const m=byReport.get(String(report.id))??[];const value=(code:string)=>m.find(x=>x.metric_code===code);const avg=value('FINAL_HTVI_AVERAGE');const finalCount=value('FINAL_IMPACT_REPORTS');return <article key={String(report.id)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold text-slate-500">REPORTING YEAR</p><h2 className="mt-1 text-2xl font-black">{String(report.reporting_year)}</h2></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black">{String(report.status)}</span></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-500">الأنشطة</span><strong className="mt-1 block text-2xl">{String(value('ACTIVITIES_TOTAL')?.metric_value??0)}</strong></div><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-500">التقارير النهائية</span><strong className="mt-1 block text-2xl">{String(finalCount?.metric_value??0)}</strong></div><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-500">متوسط HTVI النهائي</span><strong className="mt-1 block text-2xl">{avg?.metric_value==null?'—':Number(avg.metric_value).toFixed(1)}</strong></div><div className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-500">Coverage denominator</span><strong className="mt-1 block text-2xl">{String(avg?.denominator??0)}</strong></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><Link href={`/annual-reports/${String(report.id)}`} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold">عرض / طباعة</Link><div className="flex flex-wrap gap-2">{canApprove&&String(report.status)==='CHAIR_REVIEW'?<form action={approveAnnualReportAction}><input type="hidden" name="reportId" value={String(report.id)}/><button className="rounded-xl bg-teal-900 px-4 py-2.5 text-sm font-bold text-white">اعتماد رئيس اللجنة</button></form>:null}{canAck&&String(report.status)==='SUBMITTED_TO_MANAGEMENT'?<form action={acknowledgeAnnualReportAction} className="flex gap-2"><input type="hidden" name="reportId" value={String(report.id)}/><input name="comment" placeholder="تعليق إداري اختياري" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><button className="rounded-xl bg-violet-900 px-4 py-2.5 text-sm font-bold text-white">إقرار الاستلام</button></form>:null}</div></div></article>})}</div>
  </section>;
}
