import { roleHasPermission } from '@/lib/auth/permissions';
import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { activateTemplateAction, markTemplateQaAction, uploadTemplateVersionAction } from './actions';

export default async function TemplatesAdminPage(){
  const c=await requireServerAuthContext(); const canManage=roleHasPermission(c.activeRole,'template.manage'); const canApprove=roleHasPermission(c.activeRole,'template.approve'); if(!canManage&&!canApprove)throw new Error('غير مصرح بإدارة القوالب.');
  const s=await createServerSupabaseClient(); const {data:templates,error}=await s.from('document_templates').select('*,template_versions(*,template_mapping_versions(*))').eq('organization_id',c.organizationId).order('created_at',{ascending:false}); if(error)throw new Error('تعذر تحميل القوالب.');
  return <section className="space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Template Lifecycle</p><h1 className="mt-2 text-3xl font-black">إدارة القوالب والإصدارات</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">النموذج الرسمي والقوالب الداخلية منفصلة، وكل إصدار يحتفظ بالملف والـchecksum وخريطة الحقول ونتيجة Visual/Regression QA قبل التفعيل. السجلات التاريخية لا تُهاجر بصمت.</p></header>
    {canManage?<details open className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer font-black">إضافة إصدار Template جديد</summary><form action={uploadTemplateVersionAction} className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Template Code<input name="templateCode" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5" dir="ltr"/></label><label className="text-xs font-bold">العائلة<select name="family" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option>OFFICIAL_EXTERNAL_FORM</option><option>INTERNAL_GOVERNANCE</option><option>REPORT</option></select></label><label className="text-xs font-bold">الاسم العربي<input name="nameAr" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">English Name<input name="nameEn" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5" dir="ltr"/></label><label className="text-xs font-bold">Version<input name="version" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5" dir="ltr"/></label><label className="text-xs font-bold">Source reference<input name="sourceReference" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold md:col-span-2">ملف PDF/DOCX<input type="file" name="file" required accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold md:col-span-2">Field Mapping JSON<textarea name="mappingJson" defaultValue="[]" dir="ltr" className="mt-2 min-h-24 w-full rounded-xl border border-slate-300 p-3 font-mono text-xs"/></label><button className="justify-self-end rounded-xl bg-teal-800 px-5 py-3 text-sm font-black text-white md:col-span-2">رفع وحفظ الإصدار Draft</button></form></details>:null}
    <div className="grid gap-4">{(templates??[]).map(t=><article key={String(t.id)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><div className="font-mono text-xs font-bold text-slate-500" dir="ltr">{String(t.template_code)}</div><h2 className="mt-1 text-xl font-black">{String(t.name_ar)}</h2><p className="text-xs text-slate-500">{String(t.template_family)}</p></div><div className="mt-4 space-y-3">{((t.template_versions??[]) as Array<Record<string,unknown>>).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(v=>{const mappings=(v.template_mapping_versions??[]) as Array<Record<string,unknown>>;return <div key={String(v.id)} className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><span><strong>v{String(v.version_label)}</strong> · {String(v.status)}</span><span className="font-mono text-[10px] text-slate-500" dir="ltr">{String(v.checksum).slice(0,16)}…</span></div><div className="mt-2 text-xs text-slate-500">Visual QA: {String(v.visual_qa_status)} · Mapping QA: {String(mappings[0]?.regression_test_status??'PENDING')}</div><div className="mt-3 flex flex-wrap gap-2">{canManage&&String(v.status)==='DRAFT'?<form action={markTemplateQaAction} className="flex flex-wrap gap-2"><input type="hidden" name="versionId" value={String(v.id)}/><select name="visualQa" className="rounded-lg border border-slate-300 bg-white px-2 py-2 text-xs"><option>PASSED</option><option>FAILED</option></select><select name="regressionQa" className="rounded-lg border border-slate-300 bg-white px-2 py-2 text-xs"><option>PASSED</option><option>FAILED</option></select><button className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold">حفظ QA</button></form>:null}{canApprove&&String(v.status)==='DRAFT'&&String(v.visual_qa_status)==='PASSED'&&String(mappings[0]?.regression_test_status)==='PASSED'?<form action={activateTemplateAction} className="flex gap-2"><input type="hidden" name="versionId" value={String(v.id)}/><input type="date" name="effectiveFrom" required className="rounded-lg border border-slate-300 px-2 py-2 text-xs"/><button className="rounded-lg bg-violet-900 px-3 py-2 text-xs font-bold text-white">تفعيل الإصدار</button></form>:null}</div></div>})}</div></article>)}</div>
  </section>;
}
