import Link from 'next/link';
import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { actPlanningSuggestionAction, suggestGapStructureAction, suggestObjectiveStructureAction } from './actions';

export default async function PlanningAssistantPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const c=await requireServerAuthContext('ai.run_prereview'); const s=await createServerSupabaseClient();
  const [activityQ,profileQ,objectivesQ,suggestionsQ]=await Promise.all([
    s.from('activities').select('activity_code,title_ar,title_en,internal_state').eq('id',id).eq('organization_id',c.organizationId).single(),
    s.from('activity_intake_profiles').select('learning_gap,aim_and_outcomes,learning_methods,participant_evaluation_method').eq('activity_id',id).eq('organization_id',c.organizationId).maybeSingle(),
    s.from('activity_learning_objectives').select('id,objective_text,learning_domain,sort_order').eq('activity_id',id).eq('organization_id',c.organizationId).order('sort_order'),
    s.from('ai_suggestions').select('*').eq('activity_id',id).eq('organization_id',c.organizationId).order('created_at',{ascending:false}).limit(30),
  ]);
  if(activityQ.error||profileQ.error||objectivesQ.error||suggestionsQ.error)throw new Error('تعذر تحميل مساعد التخطيط.');
  const activity=activityQ.data; const profile=profileQ.data; const open=(suggestionsQ.data??[]).filter(x=>x.status==='PROPOSED');
  return <section className="space-y-6"><div className="flex gap-2 text-sm"><Link href={`/activities/${id}/intake`} className="font-bold text-teal-800">ملف النشاط</Link><span className="text-slate-400">/</span><span>Planning Assistant</span></div>
    <header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Human-in-the-loop Planning Assistant</p><div className="mt-2 font-mono text-xs font-bold text-slate-500" dir="ltr">{String(activity.activity_code)}</div><h1 className="mt-1 text-3xl font-black">مساعد التخطيط والأهداف</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">المساعد لا يكتب في النموذج الرسمي تلقائيًا. كل اقتراح يبقى Proposed حتى Accept أو Edit & Accept. أي Placeholder داخل أقواس مربعة يجب حسمه يدويًا قبل الاعتماد حتى لا تتحول معلومة ناقصة إلى حقيقة مصطنعة.</p></header>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">Learning Gap</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-600">يحافظ الاقتراح على النص الموجود ويطلب منك تحديد مصدر الدليل إذا لم يكن موجودًا؛ لا ينشئ Baseline أو رقمًا أو نتيجة غير مسجلة.</p></div><form action={suggestGapStructureAction}><input type="hidden" name="activityId" value={id}/><input type="hidden" name="sourceText" value={String(profile?.learning_gap??'')}/><button className="rounded-xl border border-teal-700 px-4 py-2.5 text-sm font-bold text-teal-900">اقتراح بنية Gap</button></form></div><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-7">{String(profile?.learning_gap??'لم تُسجل فجوة تعلم بعد.')}</div></section>

    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">SMART / Bloom Objective Review</h2><p className="mt-2 text-sm leading-7 text-slate-600">الأفعال العامة مثل Understand / Know / يفهم / يعرف تُعامل كإشارة لتحسين الصياغة. القالب المقترح يحتوي Placeholders إذا كان استبدال الفعل سيحتاج معلومات غير موجودة.</p><div className="mt-5 space-y-3">{(objectivesQ.data??[]).length===0?<p className="text-sm text-slate-500">لا توجد أهداف مسجلة.</p>:(objectivesQ.data??[]).map((o,i)=><article key={String(o.id)} className="flex flex-wrap items-start justify-between gap-4 rounded-xl border border-slate-200 p-4"><div className="min-w-0 flex-1"><div className="text-xs font-bold text-slate-500">Objective {i+1} · {String(o.learning_domain??'UNCLASSIFIED')}</div><p className="mt-2 text-sm font-bold leading-7">{String(o.objective_text)}</p></div><form action={suggestObjectiveStructureAction}><input type="hidden" name="activityId" value={id}/><input type="hidden" name="objectiveId" value={String(o.id)}/><input type="hidden" name="sourceText" value={String(o.objective_text)}/><button className="rounded-xl border border-slate-300 px-3 py-2 text-xs font-bold">تحليل / اقتراح</button></form></article>)}</div></section>

    <section className="rounded-2xl border border-violet-200 bg-violet-50/40 p-5"><h2 className="text-xl font-black text-violet-950">الاقتراحات المفتوحة</h2><p className="mt-2 text-xs leading-6 text-violet-800">Accept يستخدم النص المقترح كما هو ويُرفض آليًا إذا بقي Placeholder. Edit & Accept يستخدم النص الذي عدلته أنت. Reject لا يغير أي حقل.</p><div className="mt-5 space-y-4">{open.length===0?<p className="text-sm text-violet-800">لا توجد اقتراحات مفتوحة.</p>:open.map(x=><article key={String(x.id)} className="rounded-2xl border border-violet-200 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="text-xs font-black text-violet-700">{String(x.suggestion_type)} · {String(x.suggestion_origin)}</div><p className="mt-2 text-xs text-slate-500">Source: {String(x.source_text??'—')}</p></div><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-800">PROPOSED</span></div><form action={actPlanningSuggestionAction} className="mt-4 space-y-3"><input type="hidden" name="activityId" value={id}/><input type="hidden" name="suggestionId" value={String(x.id)}/><textarea name="acceptedText" defaultValue={String(x.suggested_text)} className="min-h-28 w-full rounded-xl border border-slate-300 p-3 text-sm leading-7"/><div className="flex flex-wrap gap-2"><button name="action" value="ACCEPT" className="rounded-xl bg-teal-800 px-4 py-2.5 text-xs font-black text-white">Accept</button><button name="action" value="EDIT_ACCEPT" className="rounded-xl border border-teal-700 px-4 py-2.5 text-xs font-black text-teal-900">Edit & Accept</button><button name="action" value="REJECT" className="rounded-xl border border-red-200 px-4 py-2.5 text-xs font-black text-red-700">Reject</button></div></form></article>)}</div></section>
  </section>;
}
