import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';

type AuditSearchParams={action?:string;entity?:string};

export default async function AuditTrailPage({searchParams}:{searchParams:Promise<AuditSearchParams>}){
  const context=await requireServerAuthContext('audit.view');
  const params=await searchParams; const action=(params.action??'').trim().slice(0,80); const entity=(params.entity??'').trim().slice(0,80);
  const supabase=await createServerSupabaseClient();
  let query=supabase.from('audit_logs').select('event_sequence,event_id,user_id,role_context,action,entity_type,entity_id,occurred_at,previous_hash,event_hash').eq('organization_id',context.organizationId).order('event_sequence',{ascending:false}).limit(200);
  if(action)query=query.ilike('action',`%${action}%`); if(entity)query=query.eq('entity_type',entity);
  const {data,error}=await query; if(error)throw new Error('تعذر تحميل سجل التدقيق ضمن صلاحية المؤسسة.');
  const rows=data??[];
  return <section className="space-y-6">
    <header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Immutable Audit Trail</p><h1 className="mt-2 text-3xl font-black">سجل التدقيق</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">عرض قراءة فقط لأحدث 200 حدث داخل المؤسسة الحالية. يوضح كل صف من نفّذ الإجراء، وبأي دور، وعلى أي كيان، مع بصمة تربطه بالحدث السابق.</p><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-6 text-amber-900">السجل Append-only: لا توفر الواجهة تعديلًا أو حذفًا. ظهور الحدث هنا لا يعني نجاح نتيجة الأعمال وحده؛ افحص الإجراء والكيان والقيم المرتبطة عند التحقيق.</div></header>
    <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_1fr_auto] sm:items-end" method="get"><label className="text-xs font-bold">البحث في رمز الإجراء<input name="action" defaultValue={action} placeholder="مثال: activity أو impact" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5" dir="ltr"/></label><label className="text-xs font-bold">نوع الكيان المطابق<input name="entity" defaultValue={entity} placeholder="مثال: activity" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5" dir="ltr"/></label><button className="rounded-xl bg-teal-900 px-5 py-3 text-sm font-black text-white">تطبيق المرشح</button></form>
    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><h2 className="font-black">الأحداث المطابقة</h2><p className="mt-1 text-[10px] text-slate-500">الأحدث أولًا</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{rows.length} حدث</span></div>{rows.length===0?<div className="p-10 text-center text-sm text-slate-500">لا توجد أحداث مطابقة داخل نطاق المؤسسة.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead className="bg-slate-50 text-right text-[11px] text-slate-500"><tr><th className="px-4 py-3">التسلسل / الوقت</th><th className="px-4 py-3">الإجراء</th><th className="px-4 py-3">الدور المنفذ</th><th className="px-4 py-3">الكيان</th><th className="px-4 py-3">المستخدم</th><th className="px-4 py-3">سلسلة البصمة</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row=><tr key={String(row.event_id)} className="align-top"><td className="px-4 py-4"><strong className="font-mono text-xs" dir="ltr">#{String(row.event_sequence)}</strong><div className="mt-1 text-[10px] text-slate-500" dir="ltr">{formatDate(row.occurred_at)}</div></td><td className="px-4 py-4"><strong className="font-mono text-xs text-teal-900" dir="ltr">{String(row.action)}</strong></td><td className="px-4 py-4"><span className="rounded-full bg-violet-50 px-2.5 py-1 text-[10px] font-bold text-violet-900" dir="ltr">{String(row.role_context)}</span></td><td className="px-4 py-4"><div className="font-mono text-xs" dir="ltr">{String(row.entity_type??'—')}</div><div className="mt-1 max-w-44 truncate font-mono text-[9px] text-slate-400" dir="ltr">{String(row.entity_id??'—')}</div></td><td className="px-4 py-4"><span className="font-mono text-[10px] text-slate-500" dir="ltr">{shortId(row.user_id)}</span></td><td className="px-4 py-4"><div className="font-mono text-[9px] text-slate-500" dir="ltr">prev {shortHash(row.previous_hash)}</div><div className="mt-1 font-mono text-[9px] font-bold text-slate-800" dir="ltr">hash {shortHash(row.event_hash)}</div></td></tr>)}</tbody></table></div>}</div>
  </section>;
}

function formatDate(value:unknown){const date=new Date(String(value));return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(date)}
function shortId(value:unknown){const text=String(value??'—');return text==='—'?text:`${text.slice(0,8)}…${text.slice(-4)}`}
function shortHash(value:unknown){const text=String(value??'GENESIS');return text==='GENESIS'?text:`${text.slice(0,14)}…`}
