import Link from 'next/link';
import { PrintButton } from '@/components/print-button';
import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export default async function ImpactAnnexPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const c=await requireServerAuthContext('impact.view'); const supabase=await createServerSupabaseClient();
  const [aQ,oQ]=await Promise.all([supabase.from('activities').select('activity_code,title_ar').eq('id',id).eq('organization_id',c.organizationId).single(),supabase.from('impact_objectives').select('*').eq('activity_id',id).eq('organization_id',c.organizationId).order('id')]);
  if(aQ.error||oQ.error)throw new Error('تعذر تحميل الملحق.');
  return <section className="space-y-4"><div className="no-print flex justify-between gap-3"><Link href={`/impact/${id}`} className="font-bold text-teal-800">← العودة</Link><PrintButton label="طباعة الملحق"/></div><article className="mx-auto max-w-5xl rounded-2xl bg-white p-8 shadow-sm"><div className="border-b-4 border-teal-700 pb-5"><div className="font-mono text-xs font-bold text-slate-500" dir="ltr">{String(aQ.data.activity_code)}</div><h1 className="mt-2 text-3xl font-black">Detailed Impact Annex</h1><p className="mt-1 text-sm text-slate-600">{String(aQ.data.title_ar)}</p></div><table className="mt-6 w-full border-collapse text-xs"><thead><tr className="bg-slate-50"><th className="border p-2">#</th><th className="border p-2 text-right">الهدف</th><th className="border p-2">المجال</th><th className="border p-2">الاتجاه</th><th className="border p-2">Baseline</th><th className="border p-2">Target</th><th className="border p-2">Post</th><th className="border p-2">Achievement</th><th className="border p-2">Weight</th></tr></thead><tbody>{(oQ.data??[]).map((o,i)=><tr key={String(o.id)}><td className="border p-2 text-center">{i+1}</td><td className="border p-2">{String(o.objective_text)}</td><td className="border p-2">{String(o.impact_domain)}</td><td className="border p-2">{String(o.direction)}</td><td className="border p-2 text-center">{String(o.baseline??'—')}</td><td className="border p-2 text-center">{String(o.target)}</td><td className="border p-2 text-center">{String(o.post_value??'—')}</td><td className="border p-2 text-center">{Number(o.achievement).toFixed(1)}%</td><td className="border p-2 text-center">{String(o.weight)}</td></tr>)}</tbody></table></article></section>;
}
