import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { inviteOrganizationUserAction, setMembershipStatusAction, setOrganizationUserRolesAction } from './actions';

export default async function OrganizationUsersPage(){
  const c=await requireServerAuthContext('organization.users.manage'); const s=await createServerSupabaseClient();
  const [{data:users,error:usersError},{data:roles,error:rolesError}]=await Promise.all([
    s.rpc('list_organization_users_command',{p_organization_id:c.organizationId,p_role_context:c.activeRole}),
    s.from('roles').select('code,name_ar,name_en').eq('scope','ORGANIZATION').order('code'),
  ]);
  if(usersError||rolesError)throw new Error('تعذر تحميل المستخدمين والأدوار.');
  return <section className="space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Organization Access Administration</p><h1 className="mt-2 text-3xl font-black">المستخدمون والأدوار</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">إدارة عضوية المؤسسة والأدوار منفصلة عن القرار العلمي. الحساب الواحد يمكن أن يحمل عدة أدوار، لكن التنفيذ الفعلي يبقى تحت Role Context واحد في كل جلسة ويُسجل في Audit.</p></header>
    <details open className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer font-black">دعوة مستخدم مؤسسي</summary><p className="mt-2 text-xs leading-6 text-slate-500">إرسال الدعوة يحتاج Supabase server secret في بيئة النشر؛ المفتاح لا يُرسل للمتصفح ولا يُحفظ في GitHub.</p><form action={inviteOrganizationUserAction} className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="text-xs font-bold">الاسم<input name="fullName" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">البريد<input type="email" name="email" required dir="ltr" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-left"/></label><button className="rounded-xl bg-teal-800 px-5 py-3 text-sm font-black text-white">إرسال الدعوة</button></form></details>
    <div className="grid gap-4">{(users??[]).map(user=>{const currentRoles=(user.role_codes??[]) as string[];const active=String(user.membership_status)==='ACTIVE';return <article key={String(user.membership_id)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-black">{String(user.display_name??user.email??'User')}</h2><p className="mt-1 text-xs text-slate-500" dir="ltr">{String(user.email??'—')}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-black ${active?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-800'}`}>{String(user.membership_status)}</span></div>
      <form action={setOrganizationUserRolesAction} className="mt-5"><input type="hidden" name="membershipId" value={String(user.membership_id)}/><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(roles??[]).map(role=><label key={String(role.code)} className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2.5 text-xs font-bold"><input type="checkbox" name="roles" value={String(role.code)} defaultChecked={currentRoles.includes(String(role.code))}/><span>{String(role.name_ar)}</span><span className="ms-auto text-[9px] text-slate-400" dir="ltr">{String(role.code)}</span></label>)}</div><button className="mt-4 rounded-xl border border-teal-700 px-4 py-2.5 text-sm font-bold text-teal-900">حفظ الأدوار</button></form>
      <form action={setMembershipStatusAction} className="mt-4 border-t border-slate-100 pt-4"><input type="hidden" name="membershipId" value={String(user.membership_id)}/><input type="hidden" name="status" value={active?'SUSPENDED':'ACTIVE'}/><button className={`rounded-xl px-4 py-2.5 text-xs font-bold ${active?'border border-red-200 text-red-700':'bg-emerald-700 text-white'}`}>{active?'تعليق العضوية':'إعادة تفعيل العضوية'}</button></form>
    </article>})}</div>
  </section>;
}
