import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { markNotificationReadAction, refreshNotificationsAction } from './actions';

export default async function NotificationsPage(){
  const c=await requireServerAuthContext('notification.view'); const s=await createServerSupabaseClient();
  const {data,error}=await s.from('notifications').select('*').eq('organization_id',c.organizationId).eq('recipient_user_id',c.user.id).order('created_at',{ascending:false}).limit(100); if(error)throw new Error('تعذر تحميل الإشعارات.');
  const unread=(data??[]).filter(n=>!n.is_read).length;
  return <section className="space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Governance Notifications</p><h1 className="mt-2 text-3xl font-black">الإشعارات والتنبيهات</h1><p className="mt-3 text-sm leading-7 text-slate-600">تنبيهات داخل التطبيق للمواعيد والاستحقاقات. البريد الإلكتروني يظل Feature Flag اختياريًا ولا يعتمد عليه تشغيل النظام.</p></div><div className="rounded-2xl bg-teal-50 px-5 py-4 text-center"><span className="text-xs text-teal-700">غير مقروء</span><strong className="block text-3xl text-teal-950">{unread}</strong></div></div></header>
    <form action={refreshNotificationsAction}><button className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold">تحديث الاستحقاقات الآن</button></form>
    <div className="grid gap-3">{(data??[]).length===0?<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">لا توجد إشعارات.</div>:(data??[]).map(n=><article key={String(n.id)} className={`rounded-2xl border p-5 shadow-sm ${n.is_read?'border-slate-200 bg-white':'border-teal-200 bg-teal-50/40'}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${n.severity==='CRITICAL'?'bg-red-100 text-red-800':n.severity==='WARNING'?'bg-amber-100 text-amber-800':'bg-slate-100 text-slate-700'}`}>{String(n.severity)}</span><span className="text-[10px] text-slate-500">{String(n.event_code)}</span></div><h2 className="mt-2 font-black">{String(n.title)}</h2><p className="mt-1 text-sm text-slate-600">{String(n.body)}</p></div>{!n.is_read?<form action={markNotificationReadAction}><input type="hidden" name="notificationId" value={String(n.id)}/><button className="rounded-xl border border-teal-700 px-3 py-2 text-xs font-bold text-teal-900">تعليم كمقروء</button></form>:null}</div></article>)}</div>
  </section>;
}
