import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { uploadReferenceDocumentAction } from './actions';

export default async function ReferenceLibraryPage(){
  const c=await requireServerAuthContext('ai.manage_references'); const s=await createServerSupabaseClient();
  const [docsQ,conflictsQ]=await Promise.all([
    s.from('reference_documents').select('id,source_code,title,source_type,authority_level,version_label,effective_from,effective_to,status,source_uri,source_storage_path,source_sha256,source_mime_type,source_file_size_bytes,verified_at,is_global').or(`organization_id.eq.${c.organizationId},organization_id.is.null`).order('authority_level').order('created_at',{ascending:false}),
    s.from('source_conflicts').select('id,rule_code,conflict_summary,status,detected_at').eq('organization_id',c.organizationId).order('detected_at',{ascending:false}),
  ]);
  if(docsQ.error||conflictsQ.error)throw new Error('تعذر تحميل مكتبة المراجع.');
  return <section className="space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Source Authority Library</p><h1 className="mt-2 text-3xl font-black">مكتبة المراجع والقواعد</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">تُحفظ ملفات المصادر الخاصة بالمؤسسة في Storage خاص مع SHA-256 والإصدار وتاريخ السريان. وجود الملف لا يحول المحتوى تلقائيًا إلى قاعدة؛ Rule Scope والإصدار يبقيان منفصلين وقابلين للتتبع.</p></header>
    <details open className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer font-black">رفع مصدر مرجعي خاص بالمؤسسة</summary><form action={uploadReferenceDocumentAction} className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Source Code<input name="sourceCode" required placeholder="SCFHS_ACTIVITY_STANDARDS_2023" dir="ltr" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">العنوان<input name="title" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">نوع المصدر<select name="sourceType" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option>REGULATORY</option><option>ACCREDITATION_STANDARD</option><option>OPERATIONAL_GUIDANCE</option><option>ETHICS</option><option>EDUCATIONAL_GUIDANCE</option><option>INTERNAL_POLICY</option></select></label><label className="text-xs font-bold">Authority Level<select name="authorityLevel" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="1">1 — Regulatory / Accreditation</option><option value="2">2 — Operational Guidance</option><option value="3">3 — Ethics</option><option value="4">4 — Educational Guidance</option><option value="5">5 — Internal Policy</option></select></label><label className="text-xs font-bold">الإصدار<input name="version" required dir="ltr" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">رابط/مرجع المصدر<input name="sourceUri" dir="ltr" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">Effective From<input type="date" name="effectiveFrom" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold">Effective To<input type="date" name="effectiveTo" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-xs font-bold md:col-span-2">PDF / DOCX<input type="file" name="file" required accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><button className="justify-self-end rounded-xl bg-teal-800 px-5 py-3 text-sm font-black text-white md:col-span-2">رفع وتسجيل المصدر</button></form></details>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">المصادر المسجلة</h2><div className="mt-4 overflow-auto"><table className="w-full min-w-[900px] border-collapse text-xs"><thead><tr className="bg-slate-50"><th className="p-3 text-right">Code / Title</th><th className="p-3">Type</th><th className="p-3">Authority</th><th className="p-3">Version</th><th className="p-3">File</th><th className="p-3">Status</th></tr></thead><tbody>{(docsQ.data??[]).map(d=><tr key={String(d.id)} className="border-t border-slate-100"><td className="p-3"><div className="font-mono font-bold" dir="ltr">{String(d.source_code)}</div><div className="mt-1 font-bold">{String(d.title)}</div></td><td className="p-3">{String(d.source_type)}</td><td className="p-3 text-center">{String(d.authority_level)}</td><td className="p-3 text-center">{String(d.version_label)}</td><td className="p-3">{d.is_global?<span className="rounded-full bg-violet-50 px-2 py-1 font-bold text-violet-800">GLOBAL METADATA</span>:d.source_sha256?<span className="font-mono text-[10px]" dir="ltr">SHA {String(d.source_sha256).slice(0,12)}…</span>:<span className="text-amber-700">No file attached</span>}</td><td className="p-3">{String(d.status)}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Source Conflict Queue</h2><p className="mt-2 text-xs leading-6 text-slate-500">أي تعارض بين مصدرين يبقى مفتوحًا للمراجعة البشرية؛ لا تختار المنصة مصدرًا بصمت.</p><div className="mt-4 space-y-2">{(conflictsQ.data??[]).length===0?<p className="text-sm text-slate-500">لا توجد تعارضات مسجلة.</p>:(conflictsQ.data??[]).map(x=><div key={String(x.id)} className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><div className="flex flex-wrap justify-between gap-3"><strong>{String(x.rule_code)}</strong><span className="text-xs font-bold">{String(x.status)}</span></div><p className="mt-2 text-xs leading-6 text-amber-950">{String(x.conflict_summary)}</p></div>)}</div></section>
  </section>;
}
