import Link from 'next/link';
import { BrandLogo } from '@/components/brand-logo';
import { PrintButton } from '@/components/print-button';
import { notFound } from 'next/navigation';
import { roleHasPermission } from '@/lib/auth/permissions';
import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';

type J=Record<string,unknown>;
export default async function MinutesPrintPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const c=await requireServerAuthContext(); if(!roleHasPermission(c.activeRole,'report.view')&&!roleHasPermission(c.activeRole,'activity.view.assigned'))notFound(); const s=await createServerSupabaseClient(); const {data,error}=await s.from('committee_minutes').select('*').eq('id',id).eq('organization_id',c.organizationId).single(); if(error)notFound();
  const snap=(data.snapshot_json??{}) as J; const activity=(snap.activity??{}) as J; const meeting=(snap.meeting??{}) as J; const committee=(snap.committee??{}) as J; const decision=(snap.decision??{}) as J; const results=(snap.collective_results??[]) as J[]; const attendance=(snap.attendance??[]) as J[];
  return <section className="minutes-print-root space-y-4"><div className="no-print flex justify-between gap-3"><div className="flex gap-3"><Link href={`/activities/${String(activity.id??activity.activity_id??'')}/dossier`} className="font-bold text-teal-800">← ملف النشاط</Link><Link href="/reports" className="font-bold text-slate-600">التقارير</Link></div><PrintButton/></div><article className="report-page mx-auto max-w-5xl bg-white p-8 shadow-sm"><header className="flex items-start gap-5 border-b-4 border-teal-700 pb-5"><BrandLogo className="h-20 w-24 shrink-0 rounded-xl"/><div><p className="text-xs font-bold text-teal-700">CPD Governance Platform · Internal Governance Record</p><h1 className="mt-2 text-3xl font-black">محضر اجتماع اللجنة العلمية المؤسسية</h1><p className="mt-1 text-sm text-slate-500">مراجعة نشاط تطوير مهني مستمر وجاهزيته للرفع</p></div></header>
    <div className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><Meta label="رقم النشاط" value={activity.activity_code}/><Meta label="عنوان النشاط" value={activity.title_ar}/><Meta label="مرجع الاجتماع" value={meeting.meeting_reference}/><Meta label="موعد الاجتماع" value={meeting.scheduled_at}/><Meta label="اللجنة" value={committee.committee_name}/><Meta label="مرجع التشكيل" value={committee.appointment_reference}/></div>
    <h2 className="mt-8 border-r-4 border-teal-700 pr-3 text-xl font-black">الحضور</h2><table className="mt-4 w-full border-collapse text-xs"><thead><tr className="bg-slate-50"><th className="border p-2 text-right">الاسم</th><th className="border p-2">الدور</th><th className="border p-2">الحالة</th></tr></thead><tbody>{attendance.map((r,i)=><tr key={i}><td className="border p-2">{String(r.full_name??'—')}</td><td className="border p-2">{String(r.role??'—')}</td><td className="border p-2">{String(r.status??'—')}</td></tr>)}</tbody></table>
    <h2 className="mt-8 border-r-4 border-teal-700 pr-3 text-xl font-black">المراجعة الجماعية</h2><table className="mt-4 w-full border-collapse text-xs"><thead><tr className="bg-slate-50"><th className="border p-2">المعيار</th><th className="border p-2">الدليل</th><th className="border p-2">النتيجة</th><th className="border p-2 text-right">الملاحظات</th></tr></thead><tbody>{results.map((r,i)=><tr key={i}><td className="border p-2">{String(r.criterion_text??r.criterion_code??'—')}</td><td className="border p-2">{String(r.evidence_availability??'—')}</td><td className="border p-2 font-bold">{String(r.assessment??'—')}</td><td className="border p-2">{String(r.notes??'—')}</td></tr>)}</tbody></table>
    <section className="mt-8 rounded-2xl border border-violet-200 bg-violet-50 p-5"><h2 className="font-black text-violet-950">قرار رئيس اللجنة</h2><div className="mt-3 text-lg font-black">{String(decision.decision??'—')}</div>{decision.decision_notes?<p className="mt-2 text-sm leading-7">{String(decision.decision_notes)}</p>:null}<p className="mt-4 border-t border-violet-200 pt-4 text-xs leading-6 text-violet-900">موافقة اللجنة هنا تعني جاهزية النشاط للرفع فقط، ولا تمثل اعتمادًا للنشاط أو للساعات من الهيئة.</p></section>
    <div className="mt-16 grid grid-cols-2 gap-16"><div className="border-t border-slate-400 pt-3 text-center text-sm">رئيس اللجنة<br/>الاسم والتوقيع</div><div className="border-t border-slate-400 pt-3 text-center text-sm">سكرتير اللجنة<br/>الاسم والتوقيع</div></div><footer className="mt-12 border-t border-slate-200 pt-3 text-center text-[10px] text-slate-500">Version {String(data.version_no)} · Status {String(data.status)} · Snapshot SHA-256 {String(data.snapshot_sha256??'—')}</footer>
  </article></section>;
}
function Meta({label,value}:{label:string;value:unknown}){return <div className="border-b border-dotted border-slate-300 py-2"><span className="text-xs text-slate-500">{label}</span><strong className="mt-1 block">{String(value??'—')}</strong></div>}
