import Link from 'next/link';
import { PrintButton } from '@/components/print-button';
import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export default async function AnnualReportPrintPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const c=await requireServerAuthContext('annual.view'); const s=await createServerSupabaseClient();
  const [rQ,mQ,cQ,aQ]=await Promise.all([s.from('annual_committee_reports').select('*').eq('id',id).eq('organization_id',c.organizationId).single(),s.from('annual_report_metrics').select('*').eq('annual_report_id',id).eq('organization_id',c.organizationId).order('metric_code'),s.from('member_contribution_metrics').select('*').eq('annual_report_id',id).eq('organization_id',c.organizationId).order('committee_role'),s.from('annual_report_acknowledgements').select('*').eq('annual_report_id',id).eq('organization_id',c.organizationId).maybeSingle()]);
  if(rQ.error||mQ.error||cQ.error||aQ.error)throw new Error('التقرير السنوي غير متاح.'); const report=rQ.data; const metrics=mQ.data??[]; const metric=(code:string)=>metrics.find(x=>x.metric_code===code);
  return <section className="annual-print-root space-y-4"><div className="no-print flex justify-between gap-3"><Link href="/annual-reports" className="font-bold text-teal-800">← التقارير السنوية</Link><PrintButton/></div><article className="report-page mx-auto max-w-5xl bg-white p-8 shadow-sm"><header className="border-b-4 border-teal-700 pb-5"><p className="text-xs font-bold text-teal-700">CPD Governance Platform · Internal Management Report</p><h1 className="mt-2 text-3xl font-black">التقرير السنوي لأداء اللجنة العلمية</h1><p className="mt-1 text-sm text-slate-500">سنة التقرير: {String(report.reporting_year)} · الحالة: {String(report.status)}</p></header>
    <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4"><Kpi title="الأنشطة" value={metric('ACTIVITIES_TOTAL')?.metric_value}/><Kpi title="الموافقات الداخلية" value={metric('COMMITTEE_APPROVED')?.metric_value}/><Kpi title="Final Impact Reports" value={metric('FINAL_IMPACT_REPORTS')?.metric_value}/><Kpi title="متوسط HTVI النهائي" value={metric('FINAL_HTVI_AVERAGE')?.metric_value==null?'—':Number(metric('FINAL_HTVI_AVERAGE')?.metric_value).toFixed(1)}/></div>
    <section className="mt-8"><h2 className="border-r-4 border-teal-700 pr-3 text-xl font-black">Coverage & Decisions</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-5"><div className="text-sm text-slate-500">HTVI Coverage</div><div className="mt-2 text-3xl font-black">{metric('HTVI_COVERAGE_PERCENT')?.metric_value==null?'—':`${Number(metric('HTVI_COVERAGE_PERCENT')?.metric_value).toFixed(1)}%`}</div><div className="mt-1 text-xs text-slate-500">Final HTVI values are aggregated only from finalized reports; denominator = {String(metric('FINAL_HTVI_AVERAGE')?.denominator??0)} eligible activities.</div></div><div className="rounded-2xl bg-slate-50 p-5 text-sm"><div className="grid grid-cols-3 gap-3 text-center"><div><span className="text-slate-500">Approved</span><strong className="mt-1 block text-2xl">{String(metric('COMMITTEE_APPROVED')?.metric_value??0)}</strong></div><div><span className="text-slate-500">Returned</span><strong className="mt-1 block text-2xl">{String(metric('COMMITTEE_RETURNED')?.metric_value??0)}</strong></div><div><span className="text-slate-500">Not approved</span><strong className="mt-1 block text-2xl">{String(metric('COMMITTEE_NOT_APPROVED')?.metric_value??0)}</strong></div></div></div></div></section>
    <section className="mt-8"><h2 className="border-r-4 border-teal-700 pr-3 text-xl font-black">مساهمة أعضاء اللجنة</h2><p className="mt-2 text-xs text-slate-500">يعدل المقام حسب الاجتماعات التي تقع فعليًا ضمن فترة تعيين العضو. لا يتم احتساب مكافأة مالية تلقائيًا.</p><div className="mt-4 overflow-auto"><table className="w-full border-collapse text-xs"><thead><tr className="bg-slate-50"><th className="border p-2 text-right">العضو</th><th className="border p-2">الدور</th><th className="border p-2">Eligible</th><th className="border p-2">Present</th><th className="border p-2">Excused</th><th className="border p-2">Attendance</th></tr></thead><tbody>{(cQ.data??[]).map(row=><tr key={String(row.id)}><td className="border p-2">{String(row.full_name_snapshot)}</td><td className="border p-2">{String(row.committee_role)}</td><td className="border p-2 text-center">{String(row.eligible_meetings)}</td><td className="border p-2 text-center">{String(row.attended_meetings)}</td><td className="border p-2 text-center">{String(row.excused_meetings)}</td><td className="border p-2 text-center">{row.attendance_rate==null?'—':`${Number(row.attendance_rate).toFixed(1)}%`}</td></tr>)}</tbody></table></div></section>
    <section className="mt-8 rounded-2xl border border-violet-200 bg-violet-50 p-5 text-sm leading-7 text-violet-950"><strong>حوكمة الاعتماد:</strong> اعتماد رئيس اللجنة هو اعتماد تقرير اللجنة الداخلي. الإقرار الإداري هو استلام/إقرار إداري ولا يغيّر القرار العلمي أو يمنح اعتمادًا خارجيًا.</section>
    <footer className="mt-10 border-t border-slate-200 pt-4 text-center text-xs text-slate-500">Chair approved: {String(report.chair_approved_at??'—')} · Management acknowledged: {String(aQ.data?.acknowledged_at??'—')}</footer>
  </article></section>;
}
function Kpi({title,value}:{title:string;value:unknown}){return <div className="rounded-2xl border border-slate-200 p-4"><span className="text-xs text-slate-500">{title}</span><strong className="mt-1 block text-2xl">{String(value??0)}</strong></div>}
