import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { requestImpactCorrectionAction, reviewImpactCorrectionAction } from './actions';

export default async function ImpactCorrectionsPage(){
  const c=await requireServerAuthContext('impact.view'); const canRequest=['ORGANIZATION_SYSTEM_ADMIN','ACTIVITY_OFFICER'].includes(c.activeRole); const canApprove=c.activeRole==='MANAGEMENT_APPROVER'; const s=await createServerSupabaseClient();
  const [requestsQ,reportsQ,activitiesQ]=await Promise.all([
    s.from('impact_correction_requests').select('*').eq('organization_id',c.organizationId).order('requested_at',{ascending:false}),
    s.from('impact_reports').select('id,activity_id,version_no,htvi_score,status,generated_at').eq('organization_id',c.organizationId).eq('kind','FINAL').order('generated_at',{ascending:false}),
    s.from('activities').select('id,activity_code,title_ar').eq('organization_id',c.organizationId),
  ]);
  if(requestsQ.error||reportsQ.error||activitiesQ.error)throw new Error('تعذر تحميل تصحيحات تقارير الأثر.'); const activities=new Map((activitiesQ.data??[]).map(a=>[String(a.id),a])); const currentFinals=(reportsQ.data??[]).filter(r=>r.status==='FINAL');
  return <section className="space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Controlled Correction Workflow</p><h1 className="mt-2 text-3xl font-black">تصحيح التقرير النهائي</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">لا يمكن تعديل مدخلات تقرير نهائي مباشرة. يبدأ التصحيح بطلب مبرر، ثم اعتماد إداري، ثم تصبح النسخة السابقة SUPERSEDED وتُفتح مرحلة الأثر لإنتاج Final Version جديدة مع بقاء النسخة التاريخية محفوظة.</p></header>
    {canRequest?<form action={requestImpactCorrectionAction} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">طلب تصحيح جديد</h2><div className="mt-4 grid gap-3 md:grid-cols-[320px_1fr_auto] md:items-end"><label className="text-xs font-bold">التقرير النهائي<select name="activityId" required className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">اختر النشاط</option>{currentFinals.map(r=>{const a=activities.get(String(r.activity_id));return <option key={String(r.id)} value={String(r.activity_id)}>{String(a?.activity_code??'—')} · {String(a?.title_ar??'Activity')} · v{String(r.version_no)}</option>})}</select></label><label className="text-xs font-bold">سبب التصحيح<input name="reason" required className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><button className="rounded-xl bg-teal-800 px-4 py-3 text-sm font-black text-white">إرسال الطلب</button></div></form>:null}
    <div className="grid gap-3">{(requestsQ.data??[]).length===0?<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">لا توجد طلبات تصحيح.</div>:(requestsQ.data??[]).map(req=>{const a=activities.get(String(req.activity_id));return <article key={String(req.id)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-mono text-xs font-bold text-slate-500" dir="ltr">{String(a?.activity_code??'—')}</div><h2 className="mt-1 font-black">{String(a?.title_ar??'Activity')}</h2><p className="mt-2 text-sm leading-7 text-slate-600">{String(req.reason)}</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black">{String(req.status)}</span></div>{canApprove&&String(req.status)==='REQUESTED'?<form action={reviewImpactCorrectionAction} className="mt-4 grid gap-3 border-t border-slate-100 pt-4 md:grid-cols-[1fr_auto_auto] md:items-end"><input type="hidden" name="requestId" value={String(req.id)}/><label className="text-xs font-bold">ملاحظة المراجع<input name="note" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><button name="decision" value="APPROVE" className="rounded-xl bg-violet-900 px-4 py-2.5 text-xs font-black text-white">اعتماد التصحيح</button><button name="decision" value="REJECT" className="rounded-xl border border-red-200 px-4 py-2.5 text-xs font-black text-red-700">رفض</button></form>:null}</article>})}</div>
  </section>;
}
