import Link from 'next/link';
import { requireServerAuthContext } from '@/lib/auth/server-context';
import { createServerSupabaseClient } from '@/lib/supabase/server';

const checks:[string,string][]=[['activity_form_ready','نموذج النشاط'],['activity_scientific_committee_ready','اللجنة العلمية الخاصة بالنشاط'],['speakers_ready','المتحدثون'],['cv_evidence_available','السير الذاتية'],['disclosure_recorded','الإفصاحات'],['committee_decision_recorded','قرار اللجنة المؤسسية'],['final_minutes_available','المحضر النهائي'],['external_decision_evidence_available','دليل القرار الخارجي'],['final_impact_report_available','تقرير الأثر النهائي']];
export default async function EvidenceReadinessPage(){
  const c=await requireServerAuthContext('evidence.readiness.view'); const s=await createServerSupabaseClient(); const {data,error}=await s.from('activity_evidence_readiness').select('*').eq('organization_id',c.organizationId).order('activity_code'); if(error)throw new Error('تعذر تحميل جاهزية الأدلة.');
  return <section className="space-y-6"><header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Evidence Readiness</p><h1 className="mt-2 text-3xl font-black">جاهزية الأدلة المؤسسية</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-slate-600">مؤشر اكتمال داخلي لمستودع الأدلة، وليس درجة امتثال أو اعتماد من الهيئة. يوضح ما هو متوفر وما يحتاج استكمالًا قبل المراجعة أو إعادة الاعتماد.</p></header>
    <div className="grid gap-4">{(data??[]).length===0?<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">لا توجد أنشطة في النطاق.</div>:(data??[]).map(row=>{const ready=checks.filter(([key])=>Boolean(row[key])).length;const percent=Math.round(ready/checks.length*100);return <article key={String(row.activity_id)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-mono text-xs font-bold text-slate-500" dir="ltr">{String(row.activity_code)}</div><h2 className="mt-1 text-xl font-black">{String(row.title_ar)}</h2><p className="mt-1 text-xs text-slate-500">{String(row.internal_state)}</p></div><div className="text-left"><strong className="text-3xl font-black text-teal-800">{percent}%</strong><div className="text-[10px] text-slate-500">Evidence completeness</div></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{checks.map(([key,label])=><div key={key} className={`flex items-center justify-between gap-2 rounded-xl px-3 py-2.5 text-xs ${row[key]?'bg-emerald-50 text-emerald-900':'bg-slate-50 text-slate-600'}`}><span>{label}</span><strong>{row[key]?'✓':'—'}</strong></div>)}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><span className={`text-xs font-bold ${Number(row.missing_evidence_count)>0?'text-red-700':'text-slate-500'}`}>Missing evidence records: {String(row.missing_evidence_count)}</span><Link href={`/activities/${String(row.activity_id)}/intake`} className="text-sm font-bold text-teal-800">فتح ملف النشاط</Link></div></article>})}</div>
  </section>;
}
